{{- $apiIsStable := eq (include "aquacloud.ingress.isStable" .) "true" -}}
apiVersion: {{ include "aquacloud.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "app.spring_petclinic_rest.name" .}}-ingress
  namespace: {{.Release.Namespace}}  
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  tls:
    - hosts:
        - {{ template "app.spring_petclinic_rest.host.name" .}}.{{ .Values.domainNamespace }}.{{ .Values.domain }}
      secretName: tls-costaisa-org
  rules:
  - host: {{ template "app.spring_petclinic_rest.host.name" .}}.{{ .Values.domainNamespace }}.{{ .Values.domain }}
    http:
      paths:
      {{- if $apiIsStable }}
      - backend:
         service:
           name: {{ template "app.spring_petclinic_rest.name" .}}-service
           port: 
             number: 9966
        path: /              
        pathType: ImplementationSpecific
      {{- else }}     
      - backend:
         serviceName: {{ template "app.spring_petclinic_rest.name" .}}-service
         servicePort: 9966
      {{- end }}
