apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petclinic-cert
  namespace: {{.Release.Namespace}}  
spec:
  isCA: true
  commonName: petclinic-cert
  secretName: petclinic-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
