apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.spring_petclinic_frontend.name" .}}-configmap
data:
  environment.js: |-
{{ .Files.Get (printf "files/spring_petclinic_frontend/%s" .Values.spring_petclinic_frontend.config.name) | indent 4}}

 