apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "app.spring_petclinic_frontend.name" .}}-hpa
  namespace: {{.Release.Namespace}}   
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "app.spring_petclinic_frontend.name" .}}-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50