apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
spec:
  project: default
  destination:
    namespace: {{.Release.Namespace}}
    name: in-cluster
  source:
    repoURL: https://cloud-computing-team21.github.io/spring-petclinic-kube-deploy/
    targetRevision: {{ .Values.argocd.chartVersion }}
    chart: spring-petclinic
