apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  namespace: {{.Release.Namespace}} 
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.tls_host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "app.spring_petclinic_frontend.name" .}}-service 
            port:
              number: 8080
      - path: /petclinic/
        pathType: Prefix
        backend:
          service:
            name: {{ template "app.spring_petclinic_rest.name" .}}-service
            port:
              number: 9966
  tls:
  - hosts:
    - {{ .Values.ingress.tls_host }}
    secretName: letsencrypt-prod