name: Upgrade petclinic deploy

on:
  workflow_dispatch:

jobs:
  deploy-helm-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Configure Kubernetes client
      uses: silverlyra/setup-aws-eks@v0.1
      with:
        cluster: ${{ vars.EKS_CLUSTER_NAME }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Install S3 plugin and add repo
      run: |
        helm plugin install https://github.com/hypnoglow/helm-s3.git
        helm repo add cct21-spring-petclinic s3://cct21-spring-petclinic
  
    - name: Package release and push it
      run: |
        helm package .
        helm s3 push ./spring-petclinic-0.1.0.tgz cct21-spring-petclinic

    - name: Deploy Helm chart
      run: |
        helm upgrade --install petclinic s3://cct21-spring-petclinic/spring-petclinic --values ./values.yaml --namespace=petclinic --create-namespace=true \
        --set spring_petclinic_rest.extraEnv."spring\.datasource\.url"=${{ vars.EKS_SPRING_DATASOURCE }} \
        --set spring_petclinic_rest.extraEnv."spring\.datasource\.username"=${{ vars.DB_USER }} \
        --set spring_petclinic_rest.extraEnv."spring\.datasource\.password"=${{ secrets.DB_PASSWORD }} \
        --set ingress.tls_host=${{ vars.INGRESS_HOST }} \
        --set ingress.tls_mail=${{ vars.INGRESS_MAIL }}