name: Initialize RDS Instance

on:
  workflow_dispatch:

jobs:
  setup-db:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy SQL files to Bastion Host
      run: |
        scp -o StrictHostKeyChecking=no ./middleware/bbdd/1-ontopharma-db-user.sql ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}:/tmp/
        scp -o StrictHostKeyChecking=no ./middleware/bbdd/2-audit-schema.sql ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}:/tmp/

    - name: Execute SQL files on RDS through Bastion Host
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} << EOF
        PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h ${{ secrets.RDS_HOST }} -p ${{ secrets.RDS_PORT }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f /tmp/1-ontopharma-db-user.sql
        PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h ${{ secrets.RDS_HOST }} -p ${{ secrets.RDS_PORT }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f /tmp/2-audit-schema.sql
        EOF
