name: Upgrade petclinic deploy

on:
  workflow_dispatch:

jobs:
  deploy-helm-chart:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Configure Kubernetes client
      uses: silverlyra/setup-aws-eks@v0.1
      with:
        cluster: ${{ vars.EKS_CLUSTER_NAME }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
        charts_dir: .
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Deploy Helm chart
      run: |
        helm repo add cct21-spring-petclinic https://cloud-computing-team21.github.io/spring-petclinic-kube-deploy
        helm upgrade --install petclinic cct21-spring-petclinic/spring-petclinic --values ./values.yaml --namespace=petclinic --create-namespace=true \
        --set spring_petclinic_rest.extraEnv."spring\.datasource\.url"=${{ vars.EKS_SPRING_DATASOURCE }} \
        --set spring_petclinic_rest.extraEnv."spring\.datasource\.username"=${{ vars.DB_USER }} \
        --set spring_petclinic_rest.extraEnv."spring\.datasource\.password"=${{ secrets.DB_PASSWORD }} \
        --set ingress.tls_host=${{ vars.INGRESS_HOST }} \
        --set ingress.tls_mail=${{ vars.INGRESS_MAIL }}